name: health_care
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase: ^9.0.3
  firebase_core: ^1.22.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - google_logo.png
    - app_icon.png
